define(function(require, exports, module) {

    'use strict';

    exports.list = '<div class="widget-post-list"></div>';

    exports.item = [
        '<div class="widget-post-list">',
        '{@each list as item,index}',
        '<div class="post-item',
        '{@if item.displayorder > +0}',
        ' post-item-top',
        '{@/if}',
        '{@if item.digest > +0}',
        ' post-item-good',
        '{@/if}',
        '{@if item.special > +0}',
        ' post-item-pay',
        '{@/if}',
        '">',
        '<div class="post-item-content">',
        '<div class="post-item-title">',
        '<a href="http://bbs.diandong.com/thread-${item.tid}" target="_blank">${item.subject}</a>',
        '{@if item.displayorder > +0}',
        '<i class="post-ico post-ico-top"></i>',
        '{@/if}',
        '{@if item.digest > +0}',
        '<i class="post-ico post-ico-good"></i>',
        '{@/if}',
        '{@if item.special > +0}',
        '<i class="post-ico post-ico-pay"></i>',
        '{@/if}',
        '</div>',
        '{@if item.attachimgs.length !== +0}',
        '<div class="post-item-images">',
        '{@each item.attachimgs as it,i}',
        '<a href="http://bbs.diandong.com/thread-${item.tid}" target="_blank"><img src="${item.attachimgs[i]}"></a>',
        '{@/each}',
        '</div>',
        '{@else}',
        '<div class="post-item-text">${item.message}</div>',
        '{@/if}',
        '<div class="post-item-detail">',
        '<div class="post-item-avatar fn-left"><a href="http://bbs.diandong.com/home.php?mod=space&uid=${item.authorid}&do=index" target="_blank"><img src="http://uc.diandong.com/avatar.php?uid=${item.authorid}&size=small"></a></div>',
        '<div class="post-item-user fn-left"><a href="http://bbs.diandong.com/home.php?mod=space&uid=${item.authorid}&do=index" target="_blank">${item.author}</a></div>',
        '<div class="post-item-time fn-left">${item.dateline}</div>',
        '<div class="post-item-data fn-right">',
        '<a href=""http://bbs.diandong.com/thread-${item.tid}" target="_blank" class="post-data-follow"><i></i>${item.views}</a>',
        '<a href="http://bbs.diandong.com/thread-${item.tid}" target="_blank" class="post-data-comment"><i></i>${item.replies}</a>',
        '<a href="http://bbs.diandong.com/thread-${item.tid}" target="_blank" class="post-data-like"><i></i>${item.recommend_add}</a>',
        '</div>',
        '</div>',
        '</div>',
        '</div>',
        '{@/each}',
        '</div>',
        '<a href="http://bbs.diandong.com/lanmu/${fid}/${typeid}/" target="_blank" class="post-list-more">查看更多帖子</a>'
    ].join('');
});
